"""
Seed danych fiszek - polskie znaki drogowe.
Zawiera główne znaki z kategorii: ostrzegawcze, zakazu, nakazu, informacyjne.
"""

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.flashcard import Flashcard, SignCategory

FLASHCARDS_DATA = [
    # === OSTRZEGAWCZE (Warning signs) ===
    ("A-1", "Niebezpieczny zakręt w prawo", SignCategory.OSTRZEGAWCZE,
     "Ostrzega o niebezpiecznym zakręcie w prawo. Należy zmniejszyć prędkość."),
    ("A-2", "Niebezpieczny zakręt w lewo", SignCategory.OSTRZEGAWCZE,
     "Ostrzega o niebezpiecznym zakręcie w lewo. Należy zmniejszyć prędkość."),
    ("A-3", "Niebezpieczne zakręty - pierwszy w prawo", SignCategory.OSTRZEGAWCZE,
     "Ostrzega o niebezpiecznych zakrętach, z których pierwszy jest w prawo."),
    ("A-4", "Niebezpieczne zakręty - pierwszy w lewo", SignCategory.OSTRZEGAWCZE,
     "Ostrzega o niebezpiecznych zakrętach, z których pierwszy jest w lewo."),
    ("A-5", "Skrzyżowanie dróg", SignCategory.OSTRZEGAWCZE,
     "Ostrzega o skrzyżowaniu dróg, na którym pierwszeństwo nie jest określone znakami."),
    ("A-6a", "Skrzyżowanie z drogą podporządkowaną po obu stronach", SignCategory.OSTRZEGAWCZE,
     "Ostrzega o skrzyżowaniu z drogą podporządkowaną występującą po obu stronach."),
    ("A-6b", "Skrzyżowanie z drogą podporządkowaną po prawej", SignCategory.OSTRZEGAWCZE,
     "Ostrzega o skrzyżowaniu z drogą podporządkowaną po stronie prawej."),
    ("A-6c", "Skrzyżowanie z drogą podporządkowaną po lewej", SignCategory.OSTRZEGAWCZE,
     "Ostrzega o skrzyżowaniu z drogą podporządkowaną po stronie lewej."),
    ("A-7", "Ustąp pierwszeństwa", SignCategory.OSTRZEGAWCZE,
     "Ostrzega o skrzyżowaniu z drogą z pierwszeństwem przejazdu. Należy ustąpić pierwszeństwa."),
    ("A-8", "Skrzyżowanie o ruchu okrężnym", SignCategory.OSTRZEGAWCZE,
     "Ostrzega o skrzyżowaniu, na którym ruch odbywa się dookoła wyspy."),
    ("A-9", "Przejazd kolejowy z zaporami", SignCategory.OSTRZEGAWCZE,
     "Ostrzega o przejeździe kolejowym wyposażonym w zapory lub półzapory."),
    ("A-10", "Przejazd kolejowy bez zapór", SignCategory.OSTRZEGAWCZE,
     "Ostrzega o przejeździe kolejowym bez zapór i półzapór."),
    ("A-11", "Nierówna droga", SignCategory.OSTRZEGAWCZE,
     "Ostrzega o odcinku drogi z nierównościami, które mogą powodować utratę kontroli nad pojazdem."),
    ("A-11a", "Próg zwalniający", SignCategory.OSTRZEGAWCZE,
     "Ostrzega o progu zwalniającym na drodze."),
    ("A-12a", "Zwężenie jezdni - dwustronne", SignCategory.OSTRZEGAWCZE,
     "Ostrzega o zwężeniu jezdni po obu stronach."),
    ("A-12b", "Zwężenie jezdni - prawostronne", SignCategory.OSTRZEGAWCZE,
     "Ostrzega o zwężeniu jezdni po stronie prawej."),
    ("A-12c", "Zwężenie jezdni - lewostronne", SignCategory.OSTRZEGAWCZE,
     "Ostrzega o zwężeniu jezdni po stronie lewej."),
    ("A-13", "Ruchomy most", SignCategory.OSTRZEGAWCZE,
     "Ostrzega o moście ruchomym lub przeprawie promowej."),
    ("A-14", "Roboty na drodze", SignCategory.OSTRZEGAWCZE,
     "Ostrzega o prowadzonych na drodze robotach."),
    ("A-15", "Śliska jezdnia", SignCategory.OSTRZEGAWCZE,
     "Ostrzega o odcinku drogi, na którym jezdnia może być śliska."),
    ("A-16", "Przejście dla pieszych", SignCategory.OSTRZEGAWCZE,
     "Ostrzega o przejściu dla pieszych."),
    ("A-17", "Dzieci", SignCategory.OSTRZEGAWCZE,
     "Ostrzega o miejscu na drodze szczególnie uczęszczanym przez dzieci."),
    ("A-18a", "Zwierzęta gospodarskie", SignCategory.OSTRZEGAWCZE,
     "Ostrzega o możliwości napotkania zwierząt gospodarskich na drodze."),
    ("A-18b", "Zwierzęta dzikie", SignCategory.OSTRZEGAWCZE,
     "Ostrzega o możliwości napotkania dzikich zwierząt na drodze."),
    ("A-19", "Boczny wiatr", SignCategory.OSTRZEGAWCZE,
     "Ostrzega o odcinku drogi, na którym mogą występować silne boczne podmuchy wiatru."),
    ("A-20", "Odcinek jezdni o ruchu dwukierunkowym", SignCategory.OSTRZEGAWCZE,
     "Ostrzega o odcinku drogi, na którym ruch odbywa się w obu kierunkach."),
    ("A-21", "Tramwaj", SignCategory.OSTRZEGAWCZE,
     "Ostrzega o przejeździe przez tory tramwajowe."),
    ("A-22", "Niebezpieczny zjazd", SignCategory.OSTRZEGAWCZE,
     "Ostrzega o znacznym spadku drogi."),
    ("A-23", "Stromy podjazd", SignCategory.OSTRZEGAWCZE,
     "Ostrzega o stromym podjeździe."),
    ("A-24", "Rowerzyści", SignCategory.OSTRZEGAWCZE,
     "Ostrzega o miejscu, w którym rowerzyści wjeżdżają na jezdnię lub przejeżdżają przez nią."),
    ("A-29", "Sygnały świetlne", SignCategory.OSTRZEGAWCZE,
     "Ostrzega o skrzyżowaniu lub przejściu dla pieszych, na którym ruch jest kierowany sygnałami świetlnymi."),
    ("A-30", "Inne niebezpieczeństwo", SignCategory.OSTRZEGAWCZE,
     "Ostrzega o niebezpieczeństwie innego rodzaju niż określone pozostałymi znakami ostrzegawczymi."),
    ("A-32", "Oszronienie jezdni", SignCategory.OSTRZEGAWCZE,
     "Ostrzega o możliwości wystąpienia oszronienia lub oblodzenia nawierzchni jezdni."),
    ("A-33", "Zator drogowy", SignCategory.OSTRZEGAWCZE,
     "Ostrzega o możliwości zatoru drogowego."),
    ("A-34", "Wypadek drogowy", SignCategory.OSTRZEGAWCZE,
     "Ostrzega o miejscu wypadku drogowego i związanych z nim utrudnieniach w ruchu."),

    # === ZAKAZU (Prohibition signs) ===
    ("B-1", "Zakaz ruchu w obu kierunkach", SignCategory.ZAKAZU,
     "Zabrania ruchu na drodze wszelkich pojazdów, kolumn pieszych oraz jeźdźców i poganiaczy."),
    ("B-2", "Zakaz wjazdu", SignCategory.ZAKAZU,
     "Zabrania wjazdu na drogę pojazdów od strony umieszczonego znaku. Dotyczy również kolumn pieszych."),
    ("B-3", "Zakaz wjazdu pojazdów silnikowych z wyjątkiem motocykli jednośladowych", SignCategory.ZAKAZU,
     "Zabrania wjazdu pojazdów silnikowych z wyjątkiem motocykli jednośladowych."),
    ("B-3a", "Zakaz wjazdu autobusów", SignCategory.ZAKAZU,
     "Zabrania wjazdu autobusów."),
    ("B-4", "Zakaz wjazdu motocykli", SignCategory.ZAKAZU,
     "Zabrania wjazdu motocykli."),
    ("B-5", "Zakaz wjazdu samochodów ciężarowych", SignCategory.ZAKAZU,
     "Zabrania wjazdu samochodów ciężarowych o dopuszczalnej masie całkowitej przekraczającej 3,5 t."),
    ("B-6", "Zakaz wjazdu ciągników rolniczych", SignCategory.ZAKAZU,
     "Zabrania wjazdu ciągników rolniczych i pojazdów wolnobieżnych."),
    ("B-7", "Zakaz wjazdu pojazdów silnikowych z przyczepą", SignCategory.ZAKAZU,
     "Zabrania wjazdu pojazdów silnikowych z przyczepą."),
    ("B-8", "Zakaz wjazdu pojazdów zaprzęgowych", SignCategory.ZAKAZU,
     "Zabrania wjazdu pojazdów zaprzęgowych."),
    ("B-9", "Zakaz wjazdu rowerów", SignCategory.ZAKAZU,
     "Zabrania wjazdu rowerów na jezdnię i pobocze."),
    ("B-10", "Zakaz wjazdu motorowerów", SignCategory.ZAKAZU,
     "Zabrania wjazdu motorowerów."),
    ("B-11", "Zakaz wjazdu wózków rowerowych", SignCategory.ZAKAZU,
     "Zabrania wjazdu wózków rowerowych."),
    ("B-12", "Zakaz wjazdu wózków ręcznych", SignCategory.ZAKAZU,
     "Zabrania wjazdu wózków ręcznych na jezdnię."),
    ("B-13", "Zakaz wjazdu pojazdów z towarami wybuchowymi lub łatwo zapalnymi", SignCategory.ZAKAZU,
     "Zabrania wjazdu pojazdów przewożących towary wybuchowe lub łatwo zapalne."),
    ("B-14", "Zakaz wjazdu pojazdów z towarami niebezpiecznymi", SignCategory.ZAKAZU,
     "Zabrania wjazdu pojazdów przewożących towary niebezpieczne."),
    ("B-15", "Zakaz wjazdu pojazdów o szerokości ponad ... m", SignCategory.ZAKAZU,
     "Zabrania wjazdu pojazdów, których szerokość (łącznie z ładunkiem) przekracza wartość podaną na znaku."),
    ("B-16", "Zakaz wjazdu pojazdów o wysokości ponad ... m", SignCategory.ZAKAZU,
     "Zabrania wjazdu pojazdów, których wysokość (łącznie z ładunkiem) przekracza wartość podaną na znaku."),
    ("B-17", "Zakaz wjazdu pojazdów o długości ponad ... m", SignCategory.ZAKAZU,
     "Zabrania wjazdu pojazdów, których długość przekracza wartość podaną na znaku."),
    ("B-18", "Zakaz wjazdu pojazdów o masie ponad ... t", SignCategory.ZAKAZU,
     "Zabrania wjazdu pojazdów, których masa rzeczywista przekracza wartość podaną na znaku."),
    ("B-19", "Zakaz wjazdu pojazdów o nacisku osi ponad ... t", SignCategory.ZAKAZU,
     "Zabrania wjazdu pojazdów, których nacisk osi przekracza wartość podaną na znaku."),
    ("B-20", "Stop", SignCategory.ZAKAZU,
     "Zakaz wjazdu bez zatrzymania się. Oznacza nakaz zatrzymania się przed drogą z pierwszeństwem."),
    ("B-21", "Zakaz skręcania w lewo", SignCategory.ZAKAZU,
     "Zabrania skręcania w lewo i zawracania. Obowiązuje na najbliższym skrzyżowaniu."),
    ("B-22", "Zakaz skręcania w prawo", SignCategory.ZAKAZU,
     "Zabrania skręcania w prawo. Obowiązuje na najbliższym skrzyżowaniu."),
    ("B-23", "Zakaz zawracania", SignCategory.ZAKAZU,
     "Zabrania zawracania od miejsca ustawienia znaku do najbliższego skrzyżowania."),
    ("B-24", "Zakaz wyprzedzania", SignCategory.ZAKAZU,
     "Zabrania wyprzedzania pojazdów wielośladowych. Nie dotyczy rowerów i motorowerów."),
    ("B-25", "Zakaz wyprzedzania przez samochody ciężarowe", SignCategory.ZAKAZU,
     "Zabrania wyprzedzania pojazdów wielośladowych przez samochody ciężarowe powyżej 3,5 t."),
    ("B-26", "Zakaz sygnałów dźwiękowych", SignCategory.ZAKAZU,
     "Zabrania używania sygnałów dźwiękowych, chyba że jest to konieczne w celu uniknięcia wypadku."),
    ("B-29", "Zakaz używania urządzeń nagłaśniających", SignCategory.ZAKAZU,
     "Zabrania używania urządzeń nagłaśniających na zewnątrz pojazdu."),
    ("B-31", "Pierwszeństwo dla nadjeżdżających z przeciwka", SignCategory.ZAKAZU,
     "Zabrania kierującemu wjazdu na zwężony odcinek drogi, jeśli zmusiłoby to jadących z przeciwka do zatrzymania."),
    ("B-33", "Ograniczenie prędkości", SignCategory.ZAKAZU,
     "Zabrania przekraczania prędkości określonej na znaku. Obowiązuje od miejsca ustawienia znaku."),
    ("B-34", "Koniec ograniczenia prędkości", SignCategory.ZAKAZU,
     "Oznacza koniec obowiązywania zakazu określonego znakiem B-33."),
    ("B-35", "Zakaz postoju", SignCategory.ZAKAZU,
     "Zabrania postoju pojazdu. Dopuszcza się zatrzymanie pojazdu na czas do 1 minuty."),
    ("B-36", "Zakaz zatrzymywania się", SignCategory.ZAKAZU,
     "Zabrania zatrzymywania i postoju pojazdu."),
    ("B-37", "Zakaz postoju w dni nieparzyste", SignCategory.ZAKAZU,
     "Zabrania postoju w dni nieparzyste miesiąca."),
    ("B-38", "Zakaz postoju w dni parzyste", SignCategory.ZAKAZU,
     "Zabrania postoju w dni parzyste miesiąca."),
    ("B-39", "Strefa ograniczonego postoju", SignCategory.ZAKAZU,
     "Oznacza wjazd do strefy, w której obowiązuje zakaz postoju pojazdów na wszystkich drogach."),
    ("B-41", "Zakaz ruchu pieszych", SignCategory.ZAKAZU,
     "Zabrania ruchu pieszych po tej stronie drogi, po której znak jest umieszczony."),
    ("B-42", "Koniec zakazów", SignCategory.ZAKAZU,
     "Oznacza koniec obowiązywania wszystkich zakazów wyrażonych znakami."),
    ("B-43", "Strefa ograniczonej prędkości", SignCategory.ZAKAZU,
     "Oznacza wjazd do strefy, w której obowiązuje ograniczenie prędkości."),
    ("B-44", "Koniec strefy ograniczonej prędkości", SignCategory.ZAKAZU,
     "Oznacza koniec strefy ograniczonej prędkości."),

    # === NAKAZU (Mandatory signs) ===
    ("C-1", "Nakaz jazdy w prawo (przed znakiem)", SignCategory.NAKAZU,
     "Nakazuje skręcenie w prawo przed znakiem."),
    ("C-2", "Nakaz jazdy w prawo (za znakiem)", SignCategory.NAKAZU,
     "Nakazuje skręcenie w prawo za znakiem."),
    ("C-3", "Nakaz jazdy w lewo (przed znakiem)", SignCategory.NAKAZU,
     "Nakazuje skręcenie w lewo przed znakiem."),
    ("C-4", "Nakaz jazdy w lewo (za znakiem)", SignCategory.NAKAZU,
     "Nakazuje skręcenie w lewo za znakiem."),
    ("C-5", "Nakaz jazdy prosto", SignCategory.NAKAZU,
     "Nakazuje jazdę prosto, zabrania skręcania i zawracania."),
    ("C-6", "Nakaz jazdy prosto lub w prawo", SignCategory.NAKAZU,
     "Nakazuje jazdę prosto lub skręcenie w prawo."),
    ("C-7", "Nakaz jazdy prosto lub w lewo", SignCategory.NAKAZU,
     "Nakazuje jazdę prosto lub skręcenie w lewo."),
    ("C-8", "Nakaz jazdy w prawo lub w lewo", SignCategory.NAKAZU,
     "Nakazuje skręcenie w prawo lub w lewo."),
    ("C-9", "Nakaz jazdy z prawej strony znaku", SignCategory.NAKAZU,
     "Nakazuje objechanie wysepki z prawej strony."),
    ("C-10", "Nakaz jazdy z lewej strony znaku", SignCategory.NAKAZU,
     "Nakazuje objechanie wysepki z lewej strony."),
    ("C-11", "Nakaz jazdy z prawej lub lewej strony znaku", SignCategory.NAKAZU,
     "Nakazuje objechanie wysepki z prawej lub lewej strony."),
    ("C-12", "Ruch okrężny", SignCategory.NAKAZU,
     "Nakazuje jazdę dookoła wyspy lub placu w kierunku wskazanym na znaku."),
    ("C-13", "Droga dla rowerów", SignCategory.NAKAZU,
     "Nakazuje kierującemu rowerem korzystanie z drogi dla rowerów."),
    ("C-13a", "Droga dla rowerów i pieszych", SignCategory.NAKAZU,
     "Oznacza drogę przeznaczoną dla rowerów i pieszych."),
    ("C-14", "Prędkość minimalna", SignCategory.NAKAZU,
     "Nakazuje jazdę z prędkością nie mniejszą niż podana na znaku."),
    ("C-15", "Koniec minimalnej prędkości", SignCategory.NAKAZU,
     "Oznacza koniec obowiązywania prędkości minimalnej."),
    ("C-16", "Droga dla pieszych", SignCategory.NAKAZU,
     "Nakazuje pieszym korzystanie z drogi przeznaczonej wyłącznie dla pieszych."),
    ("C-17", "Nakazany kierunek jazdy dla pojazdów z towarami niebezpiecznymi", SignCategory.NAKAZU,
     "Nakazuje kierującemu pojazdem przewożącym towary niebezpieczne jazdę w kierunku podanym na znaku."),
    ("C-18", "Nakaz używania łańcuchów przeciwpoślizgowych", SignCategory.NAKAZU,
     "Nakazuje zakładanie na koła łańcuchów przeciwpoślizgowych."),

    # === INFORMACYJNE (Information signs) ===
    ("D-1", "Droga z pierwszeństwem", SignCategory.INFORMACYJNE,
     "Informuje o wjeździe na drogę z pierwszeństwem przejazdu."),
    ("D-2", "Koniec drogi z pierwszeństwem", SignCategory.INFORMACYJNE,
     "Informuje o końcu drogi z pierwszeństwem przejazdu."),
    ("D-3", "Droga jednokierunkowa", SignCategory.INFORMACYJNE,
     "Informuje o wjeździe na drogę jednokierunkową."),
    ("D-4a", "Droga bez przejazdu", SignCategory.INFORMACYJNE,
     "Informuje o wjeździe na drogę bez przejazdu (ślepy zaułek)."),
    ("D-4b", "Wjazd na drogę bez przejazdu", SignCategory.INFORMACYJNE,
     "Informuje o wjeździe na drogę, z której nie ma przejazdu."),
    ("D-5", "Pierwszeństwo na zwężonym odcinku drogi", SignCategory.INFORMACYJNE,
     "Oznacza, że kierujący ma pierwszeństwo na zwężonym odcinku drogi."),
    ("D-6", "Przejście dla pieszych", SignCategory.INFORMACYJNE,
     "Informuje o przejściu dla pieszych. Kierujący zbliżając się jest zobowiązany zmniejszyć prędkość."),
    ("D-6a", "Przejazd dla rowerzystów", SignCategory.INFORMACYJNE,
     "Informuje o przejeździe dla rowerzystów. Kierujący jest zobowiązany ustąpić pierwszeństwa rowerzyście."),
    ("D-6b", "Przejście dla pieszych i przejazd dla rowerzystów", SignCategory.INFORMACYJNE,
     "Informuje o przejściu dla pieszych obok którego jest przejazd dla rowerzystów."),
    ("D-7", "Droga ekspresowa", SignCategory.INFORMACYJNE,
     "Informuje o wjeździe na drogę ekspresową. Obowiązuje prędkość minimalna 40 km/h."),
    ("D-8", "Koniec drogi ekspresowej", SignCategory.INFORMACYJNE,
     "Informuje o końcu drogi ekspresowej."),
    ("D-9", "Autostrada", SignCategory.INFORMACYJNE,
     "Informuje o wjeździe na autostradę. Obowiązuje prędkość minimalna 40 km/h."),
    ("D-10", "Koniec autostrady", SignCategory.INFORMACYJNE,
     "Informuje o końcu autostrady."),
    ("D-11", "Początek pasa ruchu dla autobusów", SignCategory.INFORMACYJNE,
     "Informuje o początku pasa ruchu przeznaczonego tylko dla autobusów."),
    ("D-12", "Koniec pasa ruchu dla autobusów", SignCategory.INFORMACYJNE,
     "Informuje o końcu pasa ruchu przeznaczonego tylko dla autobusów."),
    ("D-13", "Początek pasa ruchu powolnego", SignCategory.INFORMACYJNE,
     "Informuje o początku dodatkowego pasa ruchu na wzniesieniu dla pojazdów wolno jadących."),
    ("D-14", "Koniec pasa ruchu powolnego", SignCategory.INFORMACYJNE,
     "Informuje o końcu dodatkowego pasa ruchu na wzniesieniu."),
    ("D-15", "Przystanek autobusowy", SignCategory.INFORMACYJNE,
     "Informuje o przystanku autobusowym. Zakaz zatrzymywania w promieniu 15 m od znaku."),
    ("D-17", "Przystanek tramwajowy", SignCategory.INFORMACYJNE,
     "Informuje o przystanku tramwajowym."),
    ("D-18", "Parking", SignCategory.INFORMACYJNE,
     "Informuje o miejscu przeznaczonym na postój pojazdów."),
    ("D-18a", "Parking - Loss wskazany", SignCategory.INFORMACYJNE,
     "Informuje o parkingu z określonym sposobem ustawienia pojazdów."),
    ("D-23", "Stacja paliwowa", SignCategory.INFORMACYJNE,
     "Informuje o stacji paliw."),
    ("D-23a", "Stacja paliwowa z gazem LPG", SignCategory.INFORMACYJNE,
     "Informuje o stacji paliw z możliwością tankowania gazu LPG."),
    ("D-24", "Telefon", SignCategory.INFORMACYJNE,
     "Informuje o telefonie dostępnym dla użytkowników drogi."),
    ("D-25", "Poczta", SignCategory.INFORMACYJNE,
     "Informuje o najbliższej placówce pocztowej."),
    ("D-26", "Stacja obsługi technicznej", SignCategory.INFORMACYJNE,
     "Informuje o stacji obsługi technicznej pojazdów."),
    ("D-26b", "Wulkanizacja", SignCategory.INFORMACYJNE,
     "Informuje o warsztacie wulkanizacyjnym."),
    ("D-26c", "Myjnia", SignCategory.INFORMACYJNE,
     "Informuje o myjni samochodowej."),
    ("D-29", "Hotel (motel)", SignCategory.INFORMACYJNE,
     "Informuje o hotelu lub motelu."),
    ("D-30", "Obozowisko (camping)", SignCategory.INFORMACYJNE,
     "Informuje o obozowisku lub campingu."),
    ("D-31", "Obozowisko wyposażone w zasilanie elektryczne", SignCategory.INFORMACYJNE,
     "Informuje o obozowisku wyposażonym w zasilanie elektryczne dla przyczep kempingowych."),
    ("D-32", "Pole biwakowe", SignCategory.INFORMACYJNE,
     "Informuje o polu biwakowym."),
    ("D-33", "Schronisko młodzieżowe", SignCategory.INFORMACYJNE,
     "Informuje o schronisku młodzieżowym."),
    ("D-34", "Punkt informacji turystycznej", SignCategory.INFORMACYJNE,
     "Informuje o punkcie informacji turystycznej."),
    ("D-34a", "Informacja radiowa o ruchu drogowym", SignCategory.INFORMACYJNE,
     "Informuje o częstotliwości radiostacji nadającej informacje o ruchu drogowym."),
    ("D-35", "Przejście podziemne dla pieszych", SignCategory.INFORMACYJNE,
     "Informuje o przejściu podziemnym dla pieszych."),
    ("D-35a", "Schody ruchome w dół", SignCategory.INFORMACYJNE,
     "Informuje o schodach ruchomych prowadzących w dół."),
    ("D-36", "Przejście nadziemne dla pieszych", SignCategory.INFORMACYJNE,
     "Informuje o przejściu nadziemnym (kładce) dla pieszych."),
    ("D-36a", "Schody ruchome w górę", SignCategory.INFORMACYJNE,
     "Informuje o schodach ruchomych prowadzących w górę."),
    ("D-39", "Dopuszczalne prędkości w Polsce", SignCategory.INFORMACYJNE,
     "Informuje o dopuszczalnych prędkościach na terytorium Rzeczypospolitej Polskiej."),
    ("D-40", "Strefa zamieszkania", SignCategory.INFORMACYJNE,
     "Oznacza wjazd do strefy zamieszkania. Pieszy ma pierwszeństwo. Max prędkość 20 km/h."),
    ("D-41", "Koniec strefy zamieszkania", SignCategory.INFORMACYJNE,
     "Informuje o wyjeździe ze strefy zamieszkania."),
    ("D-42", "Obszar zabudowany", SignCategory.INFORMACYJNE,
     "Oznacza wjazd na obszar zabudowany. Obowiązuje ograniczenie prędkości do 50 km/h (w godz. 5-23) lub 60 km/h (23-5)."),
    ("D-43", "Koniec obszaru zabudowanego", SignCategory.INFORMACYJNE,
     "Informuje o wyjeździe z obszaru zabudowanego."),
    ("D-44", "Strefa parkowania", SignCategory.INFORMACYJNE,
     "Oznacza wjazd do strefy, w której parkowanie dozwolone jest tylko w miejscach wyznaczonych."),
    ("D-45", "Koniec strefy parkowania", SignCategory.INFORMACYJNE,
     "Informuje o wyjeździe ze strefy parkowania."),
    ("D-51", "Automatyczna kontrola prędkości", SignCategory.INFORMACYJNE,
     "Informuje o odcinku drogi, na którym prowadzona jest automatyczna kontrola prędkości."),
    ("D-52", "Strefa ruchu", SignCategory.INFORMACYJNE,
     "Oznacza wjazd do strefy ruchu. W strefie tej obowiązują przepisy o ruchu drogowym."),
]


async def seed_flashcards(db: AsyncSession) -> int:
    """Seed fiszek znaków drogowych."""
    count = 0
    for sign_code, sign_name, sign_category, description in FLASHCARDS_DATA:
        result = await db.execute(
            select(Flashcard).where(Flashcard.sign_code == sign_code)
        )
        if result.scalar_one_or_none():
            continue

        flashcard = Flashcard(
            sign_code=sign_code,
            sign_name=sign_name,
            sign_category=sign_category,
            description=description,
        )
        db.add(flashcard)
        count += 1

    await db.flush()
    return count
